# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: false

addons:
  apt:
    packages:
      - gmp-dev
      - libxml2-dev
      - glpk-dev
